### ISSUE TITLE
Add support for a Whisper endpoint for audio transcription

### ISSUE THREAD

**Issue by elsatch** [AugustDev/enchanted#18]
First of all, thank you for putting together this wonderful app. 

I have tried the app and could like to propose you an improvement. Right now when you press the wave icon on the right hand side of the input box it asks for permissions to send the audios to Apple for transcription and then it asks for permission to use the microphone. 

One very interesting update and upgrade would be the possibility to use your very own whisper endpoint to get audio transcription done. In this way you could have your audios transcribed in the same server as the Ollama server, without sending them to third parties.

For those people that would like to have their audio transcribed and get it typed into the input box, they could use the built-in microphone icon of the Apple keyboard, to get them processed using Apple means (on device or on their remote servers).

Thanks for considering this feature.

P.D I could write some documentation about how to setup a whisper endpoint and add that to this project documentation if required.

**Comment by AugustDev** [comment]
Hi @elsatch thanks for the suggestion. When you click "wave" icon it uses Apple Speech framework to transcribe the recording. Speech framework **does not** send recording to Apple for transcription. Instead text is transcribed on your device. You can try it out by disabling internet connection.

Assuming Apple speech recognition is good enough I don't think this feature is necessary. Please let me know if you think otherwise!
