### ISSUE TITLE
How to use the app in macOS 11?

### ISSUE THREAD

**Issue by dlcheng** [AugustDev/enchanted#60]
I have intel mac of macOS big sur, it seems that the app listed in the appstore is not compatible with the system.

Is there any way to use the app?

**Comment by mattbisme** [comment]
This software requires macOS 14 or newer. I suspect that it was written in a version of SwiftUI that doesn't exist in Big Sur. Additionally, even if it did work, you would only be able to use it to remotely access another computer running Ollama. Since Ollama isn't supported on Intel, it wouldn't make a lot of sense to support older systems.

**Comment by AugustDev** [comment]
Unfortunately Enchanted uses SDK released in latest iOS versions. Supporting lower versions of macOS would require rewriting large chunks of code, hence I would struggle to prioritise this for now. Sorry about that!
